### PR TITLE
fix(docs): Add passthrough: true to make custom controllers work agai…

### PR DESCRIPTION
**Pull request by ftischler**
…n with v5

### CODE REVIEW

**Comment by ftischler** [comment]
@willsoto I encountered issues after an update of your library from v4 to v5. I use custom controllers and checked the documentation to see about breaking changes. Just replacing the `await` with a `return` statement did not help in my case, I also had to enable `{ passthrough: true }` to get things running again. Hope this PR helps 😊 Thanks!

**Comment by willsoto** [comment]
Thanks for this. Is this change only compatible with v5 of nest?

**Comment by ftischler** [comment]
@willsoto No problem 😊 I think it is compatible with every version of Nest.js which supports the `passthrough` option in the `Res` decorator. I assume it has been added with v7 or v8. But for me it was necessary after I updated this lib from v4 to v5 because you removed `sendResponse` from the `PrometheusController`. The default behaviour of Nest.js is to not automatically send the response of a controller if `Res` is injected into a controller without `passthrough: true`

**Comment by willsoto** [comment]
Fair enough. Thanks for the explanation.

**Pull request merged**
